#ifndef PPU_DEBUG_H
#define PPU_DEBUG_H

#include "types.h"

#define PPU_NUM_SYSTEM_COLOURS 64
#define PPU_HORIZONTAL_TILES_PER_ATTRIBUTE_BYTE 4
#define PPU_VERTICAL_TILES_PER_ATTRIBUTE_BYTE 4

extern Color systemPalette[PPU_NUM_SYSTEM_COLOURS];
extern u8 attributeTableLookup[PPU_VERTICAL_TILES_PER_ATTRIBUTE_BYTE][PPU_HORIZONTAL_TILES_PER_ATTRIBUTE_BYTE];

#endif
